# 🐼 Pandas - Class 7: Merging, Joining & Concatenation
Welcome to **Class 7** of our Pandas series. Today we’ll learn how to combine multiple DataFrames using different techniques.

## 1. Using `concat()` for Stacking Data
- `pd.concat()` combines DataFrames vertically (rows) or horizontally (columns).
- Use `axis=0` for vertical stacking (default), `axis=1` for horizontal.
- `ignore_index=True` can reset the index after concatenation.

In [3]:
import pandas as pd
# Dataset 1: Product details
df1 = pd.DataFrame({
    'ProductID' : [101, 102, 103],
    'ProductName' : ['Pen', 'Notebook', 'Marker'],
    'Price' : [10, 50 , 30]
})

# Dataset 2: More products (same columns as df1 → good for vertical stacking)
df2 = pd.DataFrame({
    'ProductID' : [104, 105],
    'ProductName' : ['Pencil' , 'Eraser'],
    'Price' : [5, 4]
})
# Dataset 3: Additional info (different columns → good for horizontal stacking)
df3 = pd.DataFrame({
    'Stock' : [100, 60, 80],
    'Rating' : [4.5, 4.7,4.8]
})

print(f'DF1:{df1}')
print(f'DF2:{df2}')
print(f'DF3:{df3}')

#vertical stacking - for this cols must be same for both the dataframes(as this directly get stacked on the previously made cols)
vertical_stacking = pd.concat([df1, df2], ignore_index=True) #by default (axis = 0) - cols
print(vertical_stacking)

#horizontal stacking - for this row element size must be same for both the dataframes(as it get stacked side by side to the selected df's)
horizontal_stacking = pd.concat([df1,df3],axis=1) #rows
horizontal_stacking

DF1:   ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30
DF2:   ProductID ProductName  Price
0        104      Pencil      5
1        105      Eraser      4
DF3:   Stock  Rating
0    100     4.5
1     60     4.7
2     80     4.8
   ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30
3        104      Pencil      5
4        105      Eraser      4

   ProductID ProductName  Price  Stock  Rating
0        101         Pen     10    100     4.5
1        102    Notebook     50     60     4.7
2        103      Marker     30     80     4.8

## 2. Using `merge()` for SQL-Style Joins
- `merge()` is similar to SQL joins.
- Specify `on` or `left_on`/`right_on` to choose key columns.
- Join types: `inner` (default), `left`, `right`, `outer`.

In [ ]:
#concate df1 and df2 row wise 
product = pd.concat([df1, df2], ignore_index=True)

sales = pd.DataFrame({
    'ProductID':[101,102,104,106],
    'UnitsSold':[500,200,150,50]
})

product
sales

#1. Inner join(dono dataframe ke beech only matching productID)
inner = pd.merge(product, sales, how="inner")
print(inner)

#2. Left Join(All keys from left, matching values from right) - join type defines the usage of keys from which df 
left = pd.merge(product, sales, how="left")
print(left)

#3. Right Join(All keys from right, matched values from left.)
right = pd.merge(product, sales, how="right")
print(right)

#Outer join - return everything even the unmatched ones
outer = pd.merge(product, sales, how="outer")
print(outer)

   ProductID ProductName  Price  UnitsSold
0        101         Pen     10        500
1        102    Notebook     50        200
2        104      Pencil      5        150
   ProductID ProductName  Price  UnitsSold
0        101         Pen     10      500.0
1        102    Notebook     50      200.0
2        103      Marker     30        NaN
3        104      Pencil      5      150.0
4        105      Eraser      4        NaN
   ProductID ProductName  Price  UnitsSold
0        101         Pen   10.0        500
1        102    Notebook   50.0        200
2        104      Pencil    5.0        150
3        106         NaN    NaN         50
   ProductID ProductName  Price  UnitsSold
0        101         Pen   10.0      500.0
1        102    Notebook   50.0      200.0
2        103      Marker   30.0        NaN
3        104      Pencil    5.0      150.0
4        105      Eraser    4.0        NaN
5        106         NaN    NaN       50.0

## 3. Using `join()` with Index Alignment
- `join()` joins DataFrames on their index or on a key column.
- By default, joins on index; can specify `on='col'`.
- Useful for adding columns to an existing DataFrame.

In [ ]:
print(product)
sales = pd.DataFrame({
    'UnitSold' : [500, 200, 150, 50, 350]
}, index=[101, 102, 103, 104, 105])
print(sales)

#to use join function indices must be same for both dataframes 

#1. join stock info to products 
p_indexed = product.set_index('ProductID')
print(p_indexed)
joined = p_indexed.join(sales)
joined

#used to join the dataframes which are being joined using any one columns which is same in both dataframe

   ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30
3        104      Pencil      5
4        105      Eraser      4
     UnitSold
101       500
102       200
103       150
104        50
105       350
          ProductName  Price
ProductID
101               Pen     10
102          Notebook     50
103            Marker     30
104            Pencil      5
105            Eraser      4

          ProductName  Price  UnitSold
ProductID
101               Pen     10       500
102          Notebook     50       200
103            Marker     30       150
104            Pencil      5        50
105            Eraser      4       350

## 4. Practical Examples
- Combine sales and revenue data to see performance.
- Merge students with marks to link records.
- Practice with realistic datasets to understand alignment and missing data handling.

## Mini Practice
1. Create three DataFrames: Products, Sales, and Revenue.
2. Concatenate them vertically and horizontally.
3. Merge Sales and Revenue using different join types.
4. Join Products with Sales based on index or a key.
5. Analyze missing values after joins.

In [ ]:

# 1. Create three DataFrames: Products, Sales, and Revenue
import pandas as pd
Products = pd.DataFrame({
    'ProductID' : [101, 102, 103, 104],
    'ProductName' : ['Pen','Pencil','Notebook','Eraser'] 
})
Sales = pd.DataFrame({
    'ProductID' : [101, 102, 103, 104],
    'UnitSold' : [50, 40, 60, 30]
})
Revenue = pd.DataFrame({
    'ProductID' : [101, 102, 103, 104],
    'Amountmade' : [1000, 500, 400, 600]
})

# 2. Concatenate them vertically and horizontally
# Write your code here
vertically1 = pd.concat([Products, Revenue], axis=1)
(vertically1)
vertically2 = pd.concat([Sales,Revenue], ignore_index=True)
(vertically2)

horizontally = pd.concat([Products, Revenue], axis=1)
(horizontally)
# 3. Merge Sales and Revenue using different join types (inner, left, right, outer)
# Write your code here
inner = pd.merge(Revenue, Sales, how="inner")
print(inner)
left = pd.merge(Revenue, Sales, how='left')
print(left)
right = pd.merge(Revenue, Sales, how='right')
print(right)
outer = pd.merge(Revenue, Sales, how='outer')
print(outer)
# 4. Join Products with Sales based on index or a key
# Write your code here
Sales = pd.DataFrame({
    'Items' : ['Pen', 'Pencil', 'Eraser', 'Book'],
    'UnitSold' : [100, 20, 40, 30]
}, index=[101,102,103,104])

p_indexed = Products.set_index('ProductID')
joined = p_indexed.join(Sales)

(joined)

# 5. Analyze missing values after joins
# Use isna(), info(), or describe() to explore gaps
# Write your code here

   ProductID  Amountmade  UnitSold
0        101        1000        50
1        102         500        40
2        103         400        60
3        104         600        30
   ProductID  Amountmade  UnitSold
0        101        1000        50
1        102         500        40
2        103         400        60
3        104         600        30
   ProductID  Amountmade  UnitSold
0        101        1000        50
1        102         500        40
2        103         400        60
3        104         600        30
   ProductID  Amountmade  UnitSold
0        101        1000        50
1        102         500        40
2        103         400        60
3        104         600        30

          ProductName   Items  UnitSold
ProductID
101               Pen     Pen       100
102            Pencil  Pencil        20
103          Notebook  Eraser        40
104            Eraser    Book        30

---
## Summary
- Used `concat()` for stacking data vertically and horizontally.
- Performed SQL-style joins with `merge()`.
- Applied `join()` with index alignment.
- Explored practical use-cases like sales vs revenue, students vs marks.