# 🐼 Pandas - Class 4: Data Selection & Filtering
Welcome to **Class 4** of our Pandas series. Today we’ll explore techniques to select and filter data in a DataFrame.

## 1. Boolean Indexing & Conditional Selection
- Use comparison operators to build conditions (e.g., `df['col'] > 50`).
- Pass the condition inside `df[...]` to get matching rows.
- Combine multiple conditions with `&` (AND), `|` (OR), and `~` (NOT).
- Parentheses are required when combining conditions.

In [29]:
import pandas as pd
a = {
    "Name" : ['Devraj Singh', 'Bob Marley', 'Charlie Puth', 'David Laid', 'Emma Watson'],
    'age' : [25, 30, 35, 40, 22],
    'score' : [80, 92, 79, 85, 95]
}
b = pd.DataFrame(a)

#1. printing only true value using boolean indexing 
b[b['age'] > 27]

#2. selecting single columns with score > 85
b[b['score'] > 85]

#3. applying multiple conditions in df (multiple condition must be included in parenthesis)
b[(b.age > 27) & (b.score > 85)]
b[(b.age > 27) | (b.score > 85)]
b[~(b.score > 85)]
b[(b.age > 22) & (b.score > 80)]

         Name  age  score
1  Bob Marley   30     92
3  David Laid   40     85

## 2. Filtering Rows with Multiple Conditions
- Combine two or more conditions to refine selection.
- Remember to enclose each condition in parentheses.

In [30]:
#1. age > 25 And score > 85
b[(b.age > 25) & (b.score > 85)] 

#2. age < 35 And socre >= 90
b[(b.age < 35) & (b.score >= 90)]

#3 age between 25 and 35 (inclusive)
b[(b.age >= 25) & (b.age <= 35)]

           Name  age  score
0  Devraj Singh   25     80
1    Bob Marley   30     92
2  Charlie Puth   35     79

## 3. Using `query()` for Cleaner Filtering
- `query()` allows filtering rows with a string expression.
- It's concise and readable for complex conditions.
- Variables can be passed using the `@` symbol.

In [31]:
# df.query('condtions in english')-> eliminates the use of b[]

#1. simply Query 
print(b.query('age > 25'))

#2. multiple conditions using query -> and/&, or/| , not/~ 
print(b.query('age < 35 & score >= 85'))
print(b.query('age >= 30 and score >= 90'))

#Threshold -> @ same as f-string in python puts the exact value in the place of @
Score = 90 #variable 
print(b.query('score >= @Score'))

           Name  age  score
1    Bob Marley   30     92
2  Charlie Puth   35     79
3    David Laid   40     85
          Name  age  score
1   Bob Marley   30     92
4  Emma Watson   22     95
         Name  age  score
1  Bob Marley   30     92
          Name  age  score
1   Bob Marley   30     92
4  Emma Watson   22     95

## 4. String Operations on Columns
- Use the `.str` accessor for vectorized string methods.
- Common methods: `contains`, `replace`, `startswith`, `endswith`, `lower`, `upper`.
- Useful for cleaning or filtering text data.

In [38]:
#1. convert name to lowercase
print(b.Name.str.lower())

#2. convert name to uppercase
print(b.Name.str.upper())

#3. only captialize the first letter of words
print(b.Name.str.title())

#4. replace a substring('old_string', 'new_string')
b.Name.str.replace('Charlie', 'Charles')

#5. contains() -> check if any columns contains the condition which we included
b[b.Name.str.contains('b')]

#6. startswith() -> checks if any letter starts with alphabet
b[b.Name.str.startswith('D')]

#7. endswith() -> checks if the letter ends with given alphabet
b[b.Name.str.endswith('n')]

0    devraj singh
1      bob marley
2    charlie puth
3      david laid
4     emma watson
Name: Name, dtype: str
0    DEVRAJ SINGH
1      BOB MARLEY
2    CHARLIE PUTH
3      DAVID LAID
4     EMMA WATSON
Name: Name, dtype: str
0    Devraj Singh
1      Bob Marley
2    Charlie Puth
3      David Laid
4     Emma Watson
Name: Name, dtype: str

          Name  age  score
4  Emma Watson   22     95

## Mini Practice
1. Build a DataFrame with columns such as Name, Age, City, Score.
2. Use boolean indexing to select rows where Age > 25.
3. Filter rows where City is either 'Delhi' or 'Mumbai'.
4. Use query() to find rows with Score >= 85 and Age < 35.
5. Clean a text column using str.replace or str.lower.

In [33]:


# 1. Build a DataFrame with columns: Name, Age, City, Score


# 2. Use boolean indexing to select rows where Age > 25
# Write your code here

# 3. Filter rows where City is either 'Delhi' or 'Mumbai'
# Write your code here

# 4. Use query() to find rows with Score >= 85 and Age < 35
# Write your code here

# 5. Clean a text column using str.replace or str.lower
# Example: convert City names to lowercase or replace "delhi" with "New Delhi"
# Write your code here

---
## Summary
- Learned to use boolean indexing and conditional selection.
- Filtered rows with multiple conditions.
- Used `query()` for clean filtering.
- Applied string operations with the `.str` accessor.