# 🐼 Pandas - Class 6: GroupBy & Aggregations
Welcome to **Class 6** of our Pandas series. Today we’ll learn how to group data and perform aggregations.

## 1. Concept of Split–Apply–Combine
- **Split** the data into groups based on some criteria.
- **Apply** a function (e.g., sum, mean) to each group.
- **Combine** the results into a new DataFrame or Series.

This is the core idea behind `groupby`.

In [1]:
import pandas as pd

# New dataset: Employees, their Department, and Salary
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
  Employee Department  Salary
0     John         HR   50000
1    Sarah         IT   70000
2     Mike         IT   72000
3     Anna    Finance   65000
4      Tom    Finance   60000
5    Laura         HR   52000
6    Steve         IT   75000
7     Kate    Finance   58000

## 2. Using `groupby()` with Aggregation Functions
- Use `groupby('col').mean()` or other functions like sum, count, min, max.
- You can also use `agg()` to pass multiple functions at once.

In [ ]:
#we use groupby() to group any columns with any other columns using the first as a ref
#groupby(konsa col ko group krna)[iske basis pe].some_agg_func() = both will be the name of th cols  
#to use this groupby() feature we need to add one aggregation function

avg_salary = df.groupby('Department')['Salary'].mean()
avg_salary

#counting the no of members in each department
count_employees = df.groupby('Department')['Employee'].count()
count_employees

Department
Finance    3
HR         2
IT         3
Name: Employee, dtype: int64

## 3. Multiple Aggregations on Different Columns
- With `agg()`, you can specify different functions for each column.
- Example: `df.groupby('Dept').agg({'Salary':'mean', 'Age':'max'})`.

In [1]:
import pandas as pd

# Same dataset
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000],
    "Age": [28, 32, 30, 27, 35, 29, 31, 26]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

#to get all the aggregation values we use .agg([])
multi_stats = df.groupby('Department')['Salary'].agg(['mean', 'min', 'max'])
multi_stats

#task1 
avg_age = df.groupby('Department')['Age'].mean()
print(avg_age)

#picking two columns to perform aggregation tasks
df.groupby('Department').agg({'Salary' : ['mean', 'min', 'max'],
                              'Age' : ['min', 'max']})

Original DataFrame:
  Employee Department  Salary  Age
0     John         HR   50000   28
1    Sarah         IT   70000   32
2     Mike         IT   72000   30
3     Anna    Finance   65000   27
4      Tom    Finance   60000   35
5    Laura         HR   52000   29
6    Steve         IT   75000   31
7     Kate    Finance   58000   26
Department
Finance    29.333333
HR         28.500000
IT         31.000000
Name: Age, dtype: float64

                  Salary               Age
                    mean    min    max min max
Department
Finance     61000.000000  58000  65000  26  35
HR          51000.000000  50000  52000  28  29
IT          72333.333333  70000  75000  30  32

## 4. Pivot Tables & Crosstab
- `pivot_table()` summarizes data like Excel pivot tables.
- `crosstab()` shows frequency counts of combinations of factors.
- Both are powerful for summarizing and comparing groups.

In [3]:
#pivot_table(index = main column, values = values which is to be brought, aggfunc = aggregation functions)
print(df.pivot_table(index='Department', values=['Salary', 'Age'], aggfunc='mean')) # not used frequently

#crosstab() :-
df['Age_Group'] = pd.cut(df.Age, bins=[25,30,35,40], labels=['25-30','31-35','35-40'])
#this will create a new column in the df and will be 'Grouped' according to 'Age'
#work for numerical columns only
print(df)
pd.crosstab(df.Department, df.Age_Group)

                  Age        Salary
Department
Finance     29.333333  61000.000000
HR          28.500000  51000.000000
IT          31.000000  72333.333333
  Employee Department  Salary  Age Age_Group
0     John         HR   50000   28     25-30
1    Sarah         IT   70000   32     31-35
2     Mike         IT   72000   30     25-30
3     Anna    Finance   65000   27     25-30
4      Tom    Finance   60000   35     31-35
5    Laura         HR   52000   29     25-30
6    Steve         IT   75000   31     31-35
7     Kate    Finance   58000   26     25-30

Age_Group   25-30  31-35
Department
Finance         2      1
HR              2      0
IT              1      2

## Mini Practice
1. Create a DataFrame with columns: Department, Employee, Salary, Age, City.
2. Group by Department to get average Salary and max Age.
3. Apply multiple aggregations using agg().
4. Create a pivot_table to see mean Salary by Department and City.
5. Build a crosstab for Department vs City.

In [7]:

# 1. Create a DataFrame with columns: Department, Employee, Salary, Age, City
import pandas as pd
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000],
    "Age": [28, 32, 30, 27, 35, 29, 31, 26],
    "City" : ['Bhopal','Indore','Pune','Dehli','Bhopal','Bangalore','Dehli','Indore']
}
df = pd.DataFrame(data)
# 2. Group by Department to get average Salary and max Age
# Write your code here
print(df.groupby('Department')['Salary'].mean())
print(df.groupby('Department')['Age'].max())

# 3. Apply multiple aggregations using agg()
# Example: mean Salary, max Age per Department
# Write your code here
print(df.groupby('Department').agg({'Salary' : 'mean', 'Age' : 'max'}))

# 4. Create a pivot_table to see mean Salary by Department and City
# Write your code here
print(df.pivot_table(index='Department', values=['Salary','Age'], aggfunc=['mean', 'count']))##can pass multiple agg function inside a list 

# 5. Build a crosstab for Department vs City
# Write your code here
pd.crosstab(df.Department, df.City)

Department
Finance    61000.000000
HR         51000.000000
IT         72333.333333
Name: Salary, dtype: float64
Department
Finance    35
HR         29
IT         32
Name: Age, dtype: int64
                  Salary  Age
Department
Finance     61000.000000   35
HR          51000.000000   29
IT          72333.333333   32
                 mean               count
                  Age        Salary   Age Salary
Department
Finance     29.333333  61000.000000     3      3
HR          28.500000  51000.000000     2      2
IT          31.000000  72333.333333     3      3

City        Bangalore  Bhopal  Dehli  Indore  Pune
Department
Finance             0       1      1       1     0
HR                  1       1      0       0     0
IT                  0       0      1       1     1

---
## Summary
- Learned the split–apply–combine concept.
- Used `groupby()` with aggregation functions.
- Applied multiple aggregations to different columns.
- Explored `pivot_table` and `crosstab` for summarizing data.